---

- hosts: ansible
  become: yes
  vars:
   file_version: 1.0
  tasks:

   - name: install apache server
     yum: name=httpd state=latest
     
   - name: Ensure Apaches is running
     service: name=httpd state=started enabled=yes

   - name: install index
     template:
      src: index.html.j2
      dest: /var/www/html/index.html
      mode: 0777
