--- 
- hosts: all
  remote_user: root
  become: yes
  tasks:
    # This task updates our CentOS based systems
    - name: .rpm upgrade server
      yum: >
        update_cache=yes
        name=*
        state=latest
        update_cache=yes
      when: >
        ansible_distribution == 'CentOS'
